import AnchorIcon  from "./assets/Anchor.svg?react";
import AnchorNoCircleIcon from "./assets/AnchorNoCircle.svg?react";
import APYIcon from "./assets/APY.svg?react";
import ArrowDownIcon  from "./assets/ArrowDown.svg?react";
import BorrowAPRIcon  from "./assets/BorrowAPR.svg?react";
import BorrowValueIcon  from "./assets/BorrowValue.svg?react";
import CircleArrowRightIcon  from "./assets/CircleArrowRight.svg?react";
import CollateralValueIcon  from "./assets/CollateralValue.svg?react";
import DiscordIcon  from "./assets/Discord.svg?react";
import DollarCoinIcon  from "./assets/DollarCoin.svg?react";
import LabtopIcon  from "./assets/Labtop.svg?react";
import MenuIcon  from "./assets/Menu.svg?react";
import MenuCloseIcon  from "./assets/MenuClose.svg?react";
import MenuWalletIcon  from "./assets/MenuWallet.svg?react";
import PlusIcon  from "./assets/Plus.svg?react";
import ShieldPlusIcon  from "./assets/ShieldPlus.svg?react";
import TerraIcon  from "./assets/Terra.svg?react";
import WalletIcon  from "./assets/Wallet.svg?react";
import WalletconnectIcon  from "./assets/Walletconnect.svg?react";
import ParticipateInLiquidationsIcon  from "./assets/ParticipateInLiquidations.svg?react";
import SettingsIcon  from "./assets/Settings.svg?react";
import { createMaterialIcon } from "./createMaterialIcon";

export const Discord = createMaterialIcon(DiscordIcon);
export const Wallet = createMaterialIcon(WalletIcon);
export const ArrowDown = createMaterialIcon(ArrowDownIcon);
export const Anchor = createMaterialIcon(AnchorIcon);
export const AnchorNoCircle = createMaterialIcon(AnchorNoCircleIcon);
export const CircleArrowRight = createMaterialIcon(CircleArrowRightIcon);
export const Labtop = createMaterialIcon(LabtopIcon);
export const Menu = createMaterialIcon(MenuIcon);
export const MenuWallet = createMaterialIcon(MenuWalletIcon);
export const MenuClose = createMaterialIcon(MenuCloseIcon);
export const APY = createMaterialIcon(APYIcon);
export const BorrowAPR = createMaterialIcon(BorrowAPRIcon);
export const BorrowValue = createMaterialIcon(BorrowValueIcon);
export const CollateralValue = createMaterialIcon(CollateralValueIcon);
export const Plus = createMaterialIcon(PlusIcon);
export const Walletconnect = createMaterialIcon(WalletconnectIcon);
export const Terra = createMaterialIcon(TerraIcon);
export const ShieldPlus = createMaterialIcon(ShieldPlusIcon);
export const DollarCoin = createMaterialIcon(DollarCoinIcon);
export const ParticipateInLiquidations = createMaterialIcon(
  ParticipateInLiquidationsIcon
);
export const Settings = createMaterialIcon(SettingsIcon);
